services:
  backend:
    image: ghcr.io/tigid0u/spotish-backend:latest
    container_name: spotish-backend
    restart: unless-stopped
    environment:
      POSTGRES_USER_USERNAME: ${POSTGRES_USER_USERNAME}
      POSTGRES_USER_PASSWORD: ${POSTGRES_USER_PASSWORD}
      JDBC_URL: ${JDBC_URL}
    networks:
      - traefik_network
    labels:
      - traefik.enable=true

      # Route API calls on same domain
      - traefik.http.routers.spotish-api.rule=Host(`${APP_DOMAIN}`) && PathPrefix(`/api`)
      - traefik.http.routers.spotish-api.entrypoints=https
      - traefik.http.routers.spotish-api.tls=true
      - traefik.http.routers.spotish-api.tls.certresolver=letsencrypt

      # Strip /api before forwarding to backend (so backend sees /login not /api/login)
      - traefik.http.middlewares.spotish-api-stripprefix.stripprefix.prefixes=/api
      - traefik.http.routers.spotish-api.middlewares=spotish-api-stripprefix@docker

      # backend internal port
      - traefik.http.services.spotish-api.loadbalancer.server.port=8080

  frontend:
    image: ghcr.io/tigid0u/spotish-frontend:latest
    restart: unless-stopped
    container_name: spotish-frontend
    networks:
      - traefik_network
    labels:
      - traefik.enable=true

      # Main site
      - traefik.http.routers.spotish-web.rule=Host(`${APP_DOMAIN}`)
      - traefik.http.routers.spotish-web.entrypoints=https
      - traefik.http.routers.spotish-web.tls=true
      - traefik.http.routers.spotish-web.tls.certresolver=letsencrypt

      # nginx internal port
      - traefik.http.services.spotish-web.loadbalancer.server.port=80
networks:
  traefik_network:
    external: true
