services:
  postgresql:
    image: 'postgres:18'
    restart: unless-stopped
    container_name: spotish_db
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER_USERNAME: ${POSTGRES_USER_USERNAME}
      POSTGRES_USER_DATABASE: ${POSTGRES_USER_DATABASE}
      POSTGRES_USER_PASSWORD: ${POSTGRES_USER_PASSWORD}
    ports:
      - 5432:5432
    configs:
      - source: init-user-db
        target: /docker-entrypoint-initdb.d/00-init-user-db.sh
        mode: 0555
    volumes:
      - ./sql_scripts:/docker-entrypoint-initdb.d/sql:ro
      - pg_data:/var/lib/postgresql
    networks:
      # Attach the db container to the traefik_network
      - traefik_network

configs:
  init-user-db:
    content: |
      #!/usr/bin/env bash
      set -e

      psql -v ON_ERROR_STOP=1 <<-EOSQL
        CREATE USER $${POSTGRES_USER_USERNAME} WITH PASSWORD '$${POSTGRES_USER_PASSWORD//\'/\'\'}';
        CREATE DATABASE $${POSTGRES_USER_DATABASE} WITH OWNER = $${POSTGRES_USER_USERNAME};
        GRANT ALL PRIVILEGES ON DATABASE $${POSTGRES_USER_DATABASE} TO $${POSTGRES_USER_USERNAME};
      EOSQL

      # 2) Exécution automatique des scripts SQL (schema, triggers, data)
      #    On se connecte à la DB créée, en tant que bdr.
      files=(/docker-entrypoint-initdb.d/sql/init/*.sql)

      for f in "$${files[@]}"; do
        psql -v ON_ERROR_STOP=1 -U "$${POSTGRES_USER_USERNAME}" -d "$${POSTGRES_USER_DATABASE}" -f "$$f"
      done

volumes:
  pg_data:

networks:
  traefik_network:
    external: true
